apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: ragfrontend-catalog
spec:
  targets:
    - ./catalog/front-end.yaml
    - ./catalog/system.yaml
    - ./catalog/api-collection.yaml
    - ./catalog/pinecone-resource.yaml
    # - ./catalog/group.yaml   # enable ONLY if Group kind is allowed

