apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rag-frontend
  description: React UI for interacting with the internal RAG chatbot
  tags:
    - react
    - frontend
spec:
  type: website
  lifecycle: experimental
  owner: ai-rag-team
  system: rag-knowledge-platform
