apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: rag-query-api
  description: HTTP API for querying the RAG chatbot and managing documents
spec:
  type: openapi
  lifecycle: experimental
  owner: ai-rag-team
  definition:
    $text: ./openapi.yaml