apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: pinecone-rag-index
  description: Pinecone index used to store document embeddings for the RAG system
  tags:
    - pinecone
spec:
  type: vector-index
  owner: ai-rag-team
  system: rag-knowledge-platform